
name: Used-A-Ton Duty Bot
version: "1.0.2"
slug: used_a_ton_duty
description: Used-A-Ton Discord Duty Bot
startup: application
boot: auto
init: false

arch:
  - aarch64

options:
  daily_roster_webhook_url: ""

schema:
  daily_roster_webhook_url: str
